yolo26_runtime:
  ros__parameters:
    pc_engine_path: /home/noh/my_cv/models/yolo26s_0512.engine
    pc_ultralytics_model_path: /home/noh/my_cv/models/yolo26s_0512.engine
    pc_policy_checkpoint: /home/noh/my_cv/high_policy/rl/model_4000.pt
    pc_obs_norm_ckpt: /home/noh/my_cv/high_policy/bc/model_best.pt

    jetson_engine_path: /home/rnd/yolo26_verify/competition_0511/best_fp16.engine
    jetson_ultralytics_model_path: /home/rnd/yolo26_verify/competition_0511/best_fp16.engine
    jetson_policy_checkpoint: /home/rnd/rnd/high_policy/rl/model_4000.pt
    jetson_obs_norm_ckpt: /home/rnd/rnd/high_policy/bc/model_best.pt
